language: go
sudo: false
go:
  - 1.11.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/netscan-darwin-amd64
          - cross/netscan-darwin-amd64.md5
          - cross/netscan-darwin-amd64.sha256
          - cross/netscan-darwin-386
          - cross/netscan-darwin-386.md5
          - cross/netscan-darwin-386.sha256
          - cross/netscan-freebsd-amd64
          - cross/netscan-freebsd-amd64.md5
          - cross/netscan-freebsd-amd64.sha256
          - cross/netscan-freebsd-386
          - cross/netscan-freebsd-386.md5
          - cross/netscan-freebsd-386.sha256
          - cross/netscan-linux-arm
          - cross/netscan-linux-arm.md5
          - cross/netscan-linux-arm.sha256
          - cross/netscan-linux-arm64
          - cross/netscan-linux-arm64.md5
          - cross/netscan-linux-arm64.sha256
          - cross/netscan-linux-amd64
          - cross/netscan-linux-amd64.md5
          - cross/netscan-linux-amd64.sha256
          - cross/netscan-linux-386
          - cross/netscan-linux-386.md5
          - cross/netscan-linux-386.sha256
          - cross/netscan-solaris-amd64
          - cross/netscan-solaris-amd64.md5
          - cross/netscan-solaris-amd64.sha256
          - cross/netscan-windows-amd64
          - cross/netscan-windows-amd64.md5
          - cross/netscan-windows-amd64.sha256
          - cross/netscan-windows-386
          - cross/netscan-windows-386.md5
          - cross/netscan-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "lPK8lKvMAox5+XkLsZJV5FAkcozqqRoM85LFGBVtwMcgYJ8CL5vQ0gmRjLEgDDUpXAAjejOWuk9m4sy2FIfBC7a650JUg34oKRJBvNJKZlosRRiWRufBFlpdn2K6RQR4C3qxDfKIR6TYRS/Tjqsk880adseplyN1g2zvLpSpUYgkZ/73qefd00QwHIYpZIMeOI1z0fMZY8GCpuYlii/XwLLZR+enoTqtvNonZYJXnnKj7Cb+XqpGjL2TlCzVS2Ya4YZB3322lhVx2qsNOjhMhRmmDx57j8K8Idg9rljCU4q68pRCo98KiDDgMuLvbj1SedTqi1hz8yzAjY/yDLQSiFV31EW31Fj+d9iryc+hf5A5b/0AH36TsDTbRwf9ZACHoNFuV1ZcXqY2+owVVoUt30QBhSzbIKgFlfKMVbwRQYWSDSPMzV1YSZO2LBSYCkutwMEOpx1t4FlE39ikWibdV10Yy2rq6v+Izu7XrlCpv9/UWzc987vTM7zUHDb832Nw9lbhzXyvfTeHsyqezPBUQ46oiPQRSYFsjzT4ZownITZAGc36YEkZAdKPA5yfUpDK4ET/5OvxKoVsRtq3Dxisi0PaL4JO/vWPKFkblB2juwP6x5nFW168VmtMuG1AdRRfIIYhgowZNtYOp6ePeU75FShv2O8q+6AEEY9P9AtXYYE="
